<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; More Quarto – Advanced Modeling and Reproducibility for Educational Scientists</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./01-05-creating-tables.html" rel="next">
<link href="./01-03-introduction-to-quarto.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-d3043699f4f525e226433170f63674df.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7c121de436c7c20b050f1da4c0bef0bb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="assets/sticky-notes.css">
<link rel="stylesheet" href="assets/table-styles.css">
</head>

<body class="nav-sidebar floating fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-00-reproducibility.html">Introduction to Statistical Reproducibility</a></li><li class="breadcrumb-item"><a href="./01-04-more-quarto.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">More Quarto</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Advanced Modeling and Reproducibility for Educational Scientists</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Front Matter</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01-00-reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Statistical Reproducibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-02-project-organization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Project Organization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-03-introduction-to-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-04-more-quarto.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">More Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-05-creating-tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Creating Tables with gt</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02-00-likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Likelihood</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-01-mathematical-foundations-probability-density.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Mathematical Foundations: Probability Density</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-03-likelihood-framework-for-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Likelihood: A Framework for Evidence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-04-likelihood-framework-for-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Likelihood: A Framework for Estimation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03-00-modeling-nonlinearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modeling Nonlinearity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-01-polynomial-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Polynomial Effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-02-information-criteria-and-model-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Information Criteria and Model Selection</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-00-reproducibility.html">Introduction to Statistical Reproducibility</a></li><li class="breadcrumb-item"><a href="./01-04-more-quarto.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">More Quarto</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">More Quarto</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Quarto Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This document contains some additional instruction for EPsy 8252. Note that I might add to this as students hit me with questions over the course of the semester.</p>
<p><br></p>
<section id="code-chunks-for-figures" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="code-chunks-for-figures"><span class="header-section-number">3.1</span> Code Chunks for Figures</h2>
<p>Code chunks can be used to do anything you can do in R. For example we can fit regression models, create plots, compute summary measures, or mutate dummy variables into our data. For figures, there are a bunch of chunk options that are useful.</p>
<p>To label code chunks that include figures, we will append <code>fig-</code> to the label name. For example, we can use <code>#| label: fig-density-knowledge</code> to label a code chunk where we are creating a density plot of the news knowledge variable.</p>
<p>We can add a caption using the <code>#| fig-cap:</code> chunk option. It is also a good idea to also include the <code>#| fig-alt:</code> chunk option with figures. This provides alternative text for screenreaders (which is required under the new federal accessability laws). Below is an example of this:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "My First Quarto Document"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Hello World"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Andy and Iggy"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> html</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu"># Code Chunk</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="in">#| label: fig-density-knowledge</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-cap: "Here is your figure caption."</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-alt: "Here is alternative text for screenreaders."</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(data = pew, aes(x = knowledge)) +</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="in">   geom_density()</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Notice that by labeling this chunk with <code>fig-</code>, the figure is numbered in the document. This allows the figure to also be cross-referenced. You can do this by using the “at” symbol (@) along with the figure’s label name. For example, to cross-reference to the density plot we created, we could use something like:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "My First Quarto Document"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Hello World"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Andy and Iggy"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> html</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu"># Code Chunk</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="in">#| label: fig-density-knowledge</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-cap: "Here is your figure caption."</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-alt: "Here is alternative text for screenreaders."</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(data = pew, aes(x = knowledge)) +</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="in">   geom_density()</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>The distribution of news knowledge is unimodal (see @fig-density-knowledge).</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><br></p>
<section id="figure-size" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="figure-size"><span class="header-section-number">3.1.1</span> Figure Size</h3>
<p>There are a couple other chunk options for figures that help set the aspect ratio and size of the figure in your document. The aspect ratio is the ratio of a figure’s width to its height. We set this using the <code>#| fig-width:</code> and <code>#| fig-height:</code> chunk options. (The default value for both is 6; thus the figure appears square.) Below we change these so that the figure appears wider than it is tall.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="in">#| label: fig-density-knowledge-2</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-cap: "Density plot showing the distribution of news knowledge."</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-alt: "Density plot showing a a unimodal distribution of news knowledge."</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-width: 9</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-height: 5</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(data = pew, aes(x = knowledge)) +</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="in">   geom_density()</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-density-knowledge-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot showing a a unimodal distribution of news knowledge." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-density-knowledge-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-04-more-quarto_files/figure-html/fig-density-knowledge-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%" alt="Density plot showing a a unimodal distribution of news knowledge.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-density-knowledge-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: Density plot showing the distribution of news knowledge.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="fyi">
<p><strong>FYI</strong></p>
<p>It is important to change the aspect ratio when you have legends or when you are using <code>{patchwork}</code> to stack or put multiple figures next to each other. Many times you need to find a good aspect ratio though trial-and-error of trying different values.</p>
</div>
<p>The actual size of the figure in the document is independent of the aspect ratio and can be set using the <code>#| out-width:</code> or <code>#| out-height:</code> chunk option. These options take a character string of the direct size (in HTML documents this is typically in pixels) or of the percentage of the output width/height. Here we keep the same aspect ratio, but make the figure smaller by setting the figure width to 40% of the document’s width.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="in">#| label: fig-density-knowledge-3</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-cap: "Density plot showing the distribution of news knowledge."</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-alt: "Density plot showing a a unimodal distribution of news knowledge."</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="in">#| out-width: "40%"</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(data = pew, aes(x = news, y = knowledge)) +</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="in">   geom_point()</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-density-knowledge-3" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Density plot showing a a unimodal distribution of news knowledge." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-density-knowledge-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-04-more-quarto_files/figure-html/fig-density-knowledge-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%" alt="Density plot showing a a unimodal distribution of news knowledge.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-density-knowledge-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.2: Density plot showing the distribution of news knowledge.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="fyi">
<p><strong>PROTIP</strong></p>
<p>If you set the aspect ratio of the figure, you need only set <code>#| out-width:</code> or <code>#| out-height:</code>. You don’t need to set both as the other will be determined by the aspect ratio.</p>
</div>
<p><br></p>
</section>
</section>
<section id="inline-code-chunks-for-better-reproducibility" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="inline-code-chunks-for-better-reproducibility"><span class="header-section-number">3.2</span> Inline Code Chunks for Better Reproducibility</h2>
<p>In writing papers where there are results from data analyses being reported in the text, inline code chunks are boss! For example, consider writing the following sentence in an analysis of the <em>pew.csv</em> data.</p>
<blockquote class="blockquote">
<p>The effect of news exposure on news knowledge is 0.327 (SE = 0.09).</p>
</blockquote>
<p>Rather than computing these values and then transposing the values into the sentence, we can use inline code chunks to directly compute and write the values in the sentence. Recall, earlier we assigned the <code>tidy()</code> output into an object called <code>lm1coef</code>. The results from <code>tidy()</code> are a tibble (or data frame).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print output</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>lm1coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)   39.7      5.20        7.63 1.56e-11
2 news           0.327    0.0899      3.64 4.42e- 4</code></pre>
</div>
</div>
<p>A tibble/data frame is a combination of rows and columns. We can access different parts of the tibble by indexing the row and column that we want. For example, to access the slope standard error, which is in the 2nd row and 3rd column, we could use:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access slope SE</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>lm1coef[<span class="dv">2</span>, <span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  std.error
      &lt;dbl&gt;
1    0.0899</code></pre>
</div>
</div>
<p>Unfortunately, this also comes out as a labelled tibble. If we just want the SE value we double index this. Thus to get the value of the slope SE, we use:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access slope SE number only</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>lm1coef[[<span class="dv">2</span>, <span class="dv">3</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08994213</code></pre>
</div>
</div>
<p>Here is how we could extract the slope value and the SE of the slope value to write our earlier sentence:</p>
<blockquote class="blockquote">
<p>The effect of news exposure on news knowledge is <code>`r lm1coef[[2, 2]]`</code> (SE = <code>`r lm1coef[[2, 3]]`</code>).</p>
</blockquote>
<p>This produces the following sentence in the rendered document:</p>
<blockquote class="blockquote">
<p>The effect of news exposure on news knowledge is 0.3271158 (SE = 0.0899421).</p>
</blockquote>
<p>Note: You don’t need to assign the output to an object to index it. For example, the SE could also be extracted using: <code>`r tidy(lm.1)[[2, 2]]`</code></p>
<p><br></p>
<section id="rounding" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="rounding"><span class="header-section-number">3.2.1</span> Rounding</h3>
<p>There are several ways to set the rounding to two decimal places. One is to embed the computation in the <code>round()</code> function. For example, in the first inline chunk we could use: <code>round(lm1coef[[2, 3]], 2)</code>.</p>
<p>You can also do this in a separate code chunk and then call the values in the inline computation (as suggested in the <a href="https://quarto.org/docs/get-started/computations/rstudio.html">Quarto Computations Tutorial</a>).</p>
<p><br></p>
</section>
</section>
<section id="multiline-equations" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="multiline-equations"><span class="header-section-number">3.3</span> Multiline Equations</h2>
<p>There are a couple of ways to create multiline equations in a Quarto document. I tend to use the <code>split</code> environment from LaTeX to do this. To use this:</p>
<ul>
<li>Include <code>\begin{split}</code> and <code>\end{split}</code> in the display equation.</li>
<li>At the end of each line (where you want a linebreak) include a double backslash, <code>\\</code>.</li>
<li>In each line of the multiline equation, also include the ampersand sign (<code>&amp;</code>) at the point we want the multiple lines to align vertically.</li>
</ul>
<p>Here is an example:</p>
<pre><code>$$
\begin{split}
\hat{y}_i &amp;= 3 + 4(1) \\
&amp;= 7
\end{split}
$$</code></pre>
<p>And the resulting display equation is:</p>
<p><span class="math display">\[
\begin{split}
\hat{y}_i &amp;= 3 + 4(1) \\
&amp;= 7
\end{split}
\]</span></p>
<p>Note that the ampersand appeared immediately before the equal sign in each line of the equation, so that is where the two lines are aligned vertically (the equal signs are on top of each other). You can add as many lines to this as you want.</p>
<div class="fyi">
<p><strong>FYI</strong></p>
<p>Multiline equations are quite useful to show your work and when you have really long single equations that need to be broken up so they fit on the page (e.g., a regression equation with many predictors).</p>
</div>
<p><br></p>
<section id="spacing-out-the-lines" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="spacing-out-the-lines"><span class="header-section-number">3.3.1</span> Spacing Out the Lines</h3>
<p>You can add space between the lines of your multiline equation by including a unit of measurement between square brackets after the double backslashes.</p>
<pre><code>$$
\begin{split}
\hat{y}_i &amp;= 3 + 4(1) \\[1em]
&amp;= 7
\end{split}
$$</code></pre>
<p>Here the resulting display equation is:</p>
<p><span class="math display">\[
\begin{split}
\hat{y}_i &amp;= 3 + 4(1) \\[1em]
&amp;= 7
\end{split}
\]</span></p>
<p>Here we have added line space of 1 em. An <em>em</em> is a unit for measuring the width of printed work, equal to the height of the type size being used (typically the width of the letter “m”). Other common printing units include the <em>en</em> (the width of the letter “n”), and the <em>ex</em> (the width of the letter “x”).</p>
<!-- ::: fyi -->
<!-- Question #8 on the assignment actually asks: -->
<!-- > Use a display equation to write the equation for the underlying regression model (including error and assumptions) using Greek letters, subscripts, and variable names. Also write the equation for the fitted least squares regression equation based on the output from `lm()`. Type these two equations in the same display equation, each on a separate line of text in your document, and align the equals signs. -->
<!-- Try writing this multiline equation. -->
<!-- ::: -->
</section>
<section id="typesetting-101-hyphens-minus-signs-and-dashes" class="level3 fyi" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="typesetting-101-hyphens-minus-signs-and-dashes"><span class="header-section-number">3.3.2</span> Typesetting 101: Hyphens, Minus Signs, and Dashes</h3>
<p>In printed work the width of a hyphen, a minus sign, and dashes are all different. Quarto will correctly typeset these, but you have to indicate what you want. Below are how we indicate these in Quarto.</p>
<ul>
<li><strong>Hyphen:</strong> A hyphen is used to join two or more words together. To typeset a hyphen in Quarto, use a single hyphen; <code>-</code>.</li>
<li><strong>En Dash:</strong> An en dash is used to mark ranges and to indicate the meaning “to” in phrases like “Minneapolis–St.&nbsp;Paul”. An en dash is slightly longer than a hyphen and is typeset in Quarto using two hyphens; <code>--</code>.</li>
<li><strong>Em Dash:</strong> An em dash is used to separate extra information or mark a break in a sentence. An em dash is slightly longer than an en dash and is typeset in Quarto using three hyphens; <code>---</code>.</li>
<li><strong>Minus Sign:</strong> A minus sign is used in mathematical expressions (e.g., in subtraction or to indicate a negative number). To typeset a minus sign, use the inline equation with a single hyphen; <code>$-$</code>. When a minus sign is typeset, not only is the length of it different than a hyphen, but it also includes the correct spacing around it for mathematical typesetting.</li>
</ul>
<p>Here is a sentence incorporating each of these so you can see the differences:</p>
<p><em>During the time from January–February, my three dogs enjoy playing in the snow—apparently snow is fun for canines—with their sweaters on since it is</em> <span class="math inline">\(-30\)</span>-degrees Fahrenheit outside.</p>
<p>The input for this sentence was:</p>
<p><code>During the time from January--February, my three dogs enjoy playing in the snow---apparently snow is fun for canines---with their sweaters on since it is $-30$-degrees Fahrenheit outside.</code></p>
<p>Note that you can also typeset these in Word:</p>
<ul>
<li><strong>Hyphen:</strong> On both a Mac and PC, press “hyphen”.</li>
<li><strong>En Dash:</strong> On a Mac, press “option+hyphen key”. On a PC, press “ctrl+hyphen”.</li>
<li><strong>Em Dash:</strong> On a Mac, press “option+shift+hyphen key”. On a PC, press “alt+ctrl+hyphen”.</li>
<li><strong>Minus Sign:</strong> For a minus sign, you should use Equation Editor.</li>
</ul>
</section>
<p><br></p>
</section>
<section id="citations" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="citations"><span class="header-section-number">3.4</span> Citations</h2>
<p>To add citations, we need to:</p>
<ul>
<li>Create a BibTeX (.bib) file that holds the metadata for our references.</li>
<li>Save the BibTeX file to our project directory (typically in the <code>assets</code> directory)</li>
<li>Include <code>bibliography: "location/bibliography-name.bib"</code> in the YAML of our QMD document</li>
</ul>
<p><br></p>
<section id="creating-.bib-files-using-zotero" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="creating-.bib-files-using-zotero"><span class="header-section-number">3.4.1</span> Creating .bib Files Using Zotero</h3>
<p>Most reference managers (e.g., Papers, Zotero, Mendelay) can produce BibTex files. Here I will illustrate the process using Zotero.</p>
<ul>
<li>Create a <code>New Collection</code>.</li>
<li>Drag the references you want in your BibTeX database into this collection. For today, drag the <span class="citation" data-cites="carmichael_1954">Carmichael (<a href="#ref-carmichael_1954" role="doc-biblioref">1954</a>)</span> and <span class="citation" data-cites="ross_2020">Ross et al. (<a href="#ref-ross_2020" role="doc-biblioref">2020</a>)</span> references into this collection.</li>
<li>Right-click the collection and select <code>Export Collection</code>.</li>
<li>In the pop-up window, change the format of the exported collection to <code>BibTex</code>.</li>
<li>Click <code>OK</code>.</li>
</ul>
<p>Name the BibTex file (here I named it <code>my-bibliography.bib</code>) and save it in the <code>assets</code> folder.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/02-zotero-bibtex.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%" alt="Zotero screenshot showing exporting of BibTeX file."></p>
</figure>
</div>
</div>
</div>
<p>When you call the BibTex file in the <code>bibliography:</code> key of the YAML in your QMD document, you will need to give the location of the BibTex (relative to the QMD document) and the name you just gave it. For example if you are calling a bibliography in the quarto document <code>assignment-01.qmd</code> that has the following directory/folder structure:</p>
<pre><code>assignment-01
    ├── README
    ├── assets
       └── my-bibliography.bib
    ├── assignment-01.qmd
    ├── assignment-01.Rproj
    ├── data
       └── fertility.csv
    ├── figs
    └── scripts</code></pre>
<p><br></p>
</section>
<section id="including-the-bib-file-in-your-yaml" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="including-the-bib-file-in-your-yaml"><span class="header-section-number">3.4.2</span> Including the BIB File in your YAML</h3>
<p>You would then include the following in your Quarto document’s YAML:</p>
<pre><code>---
title: "Assignment 1"
subtitle: "Introduction to Quarto"
author: "Your Group's Names"
date: "January XX, 2023"
format: html
editor: visual
bibliography: "assets/my-bibliography.bib"
---</code></pre>
<p><br></p>
</section>
<section id="bibtex-files" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="bibtex-files"><span class="header-section-number">3.4.3</span> BibTex Files</h3>
<p>BibTeX files are essentially databases that store bibliographic information in a plain-text (style-independent) file. The database includes a set of references and their metadata. Here is the raw text inside an example BibTex file that includes two articles written by <span class="citation" data-cites="carmichael_1954">Carmichael (<a href="#ref-carmichael_1954" role="doc-biblioref">1954</a>)</span> and <span class="citation" data-cites="ross_2020">Ross et al. (<a href="#ref-ross_2020" role="doc-biblioref">2020</a>)</span>.</p>
<pre><code>@article{carmichael_1954,
    title = {Laziness and the Scholarly Life},
    volume = {78},
    number = {4},
    journal = {The Scientific Monthly},
    author = {Carmichael, Leonard},
    year = {1954},
    pages = {208--213}
}

@article{ross_2020,
    title = {Racial disparities in police use of deadly force against unarmed individuals persist after appropriately benchmarking shooting data on violent crime rates},
    issn = {1948-5506, 1948-5514},
    url = {http://journals.sagepub.com/doi/10.1177/1948550620916071},
    doi = {10.1177/1948550620916071},
    language = {en},
    urldate = {2020-06-24},
    journal = {Social Psychological and Personality Science},
    author = {Ross, Cody T. and Winterhalder, Bruce and McElreath, Richard},
    month = jun,
    year = {2020},
    pages = {194855062091607}
}</code></pre>
<p>The citation identifiers in this example are <code>carmichael_1954</code> and <code>ross_2020</code>. These identifiers are the first bit of text after the initial curly brace in the reference. This is how we will refer to the citations in our QMD document. (Typically these are auto-generated from our reference manager.) To determine the citiation identifiers, you can open your BibTeX file in RStudio. (Do this by using <code>Open File...</code> within RStudio; double-clicking on the BibTeX file will likely open it in a different application.)</p>
<p><br></p>
</section>
<section id="including-citations-in-your-quarto-document" class="level3" data-number="3.4.4">
<h3 data-number="3.4.4" class="anchored" data-anchor-id="including-citations-in-your-quarto-document"><span class="header-section-number">3.4.4</span> Including Citations in Your Quarto Document</h3>
<p>Citations go inside square brackets and are separated by semicolons. Each citation must have a key, composed of <code>@citation_identifier</code> from the database (no spaces between them). For example to cite the Carmichael article:</p>
<pre><code>Here is some text and a citation [@carmichael_1954].</code></pre>
<p>This will create a citation where you included it in the text and also add the reference at the end of the document. If you want a section header for your references, include a level-1 heading called “References” at the end of your document.</p>
<p>The rendered document now includes a citation where you added this is the QMD document. The associated reference is also included at the end of the document.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/02-citations-01.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%" alt="Screenshot of rendered Quarto document with citation."></p>
</figure>
</div>
</div>
</div>
<p>Citations may also include. additional text before and after the citation. In this example we have prefixed the citation with the word “see” and added a page number after the citation. The citation identifier and the text following the citation identifier are separated by a comma.</p>
<pre><code>Here is some text and a citation [see @carmichael_1954, p. 208].</code></pre>
<p>The output of this is:</p>
<blockquote class="blockquote">
<p>Here is some text and a citation <span class="citation" data-cites="carmichael_1954">(see <a href="#ref-carmichael_1954" role="doc-biblioref">Carmichael, 1954, p. 208</a>)</span>.</p>
</blockquote>
<p>You can also include multiple citations. To do this we include the different citation identifiers separated by a semicolon.</p>
<pre><code>Here are multiple citations [@ross_2020; @carmichael_1954].</code></pre>
<p>The output of this is:</p>
<blockquote class="blockquote">
<p>Here are multiple citations <span class="citation" data-cites="ross_2020 carmichael_1954">(<a href="#ref-carmichael_1954" role="doc-biblioref">Carmichael, 1954</a>; <a href="#ref-ross_2020" role="doc-biblioref">Ross et al., 2020</a>)</span>.</p>
</blockquote>
<p>We can also change the format of the citation. For example, here we use a format common to starting a sentence with a citation. To do that we omit the square brackets.</p>
<pre><code>@carmichael_1954 suggests something is true.</code></pre>
<p>The output of this is:</p>
<blockquote class="blockquote">
<p><span class="citation" data-cites="carmichael_1954">Carmichael (<a href="#ref-carmichael_1954" role="doc-biblioref">1954</a>)</span> suggests something is true.</p>
</blockquote>
<div class="fyi">
<p>You can learn more on the <a href="https://quarto.org/docs/authoring/footnotes-and-citations.html">Citations and Footnotes Help Page</a> in the Quarto documentation.</p>
</div>
<p><br></p>
</section>
<section id="use-apa-formatted-citations-and-references" class="level3" data-number="3.4.5">
<h3 data-number="3.4.5" class="anchored" data-anchor-id="use-apa-formatted-citations-and-references"><span class="header-section-number">3.4.5</span> Use APA Formatted Citations and References</h3>
<p>By default, citations and references are formatted using the Chicago style. To use another style, you will need to:</p>
<ul>
<li>Download the appropriate citation style language (CSL) file. (Find many at https://zotero.org/styles)</li>
<li>Place the CSL file in the <code>assets</code> folder of your project’s directory.</li>
<li>Specify the name of the CSL style file in the <code>csl:</code> key in the QMD file’s YAML.</li>
</ul>
<p>For example, say you have downloaded and saved the <code>apa.csl</code> file and placed it in the <code>assets</code> directory, giving the following directory/folder structure:</p>
<pre><code>assignment-01
    ├── README
    ├── assets
       ├── apa.csl
       └── my-bibliography.bib
    ├── assignment-01.qmd
    ├── assignment-01.Rproj
    ├── data
       └── fertility.csv
    ├── figs
    └── scripts</code></pre>
<p>You would include the following in your YAML.</p>
<p>If, for example, you had named the BIB file <code>my-bibliography.bib</code> and had put this file in the <code>assets</code> directory, your YAML would be:</p>
<pre><code>---
title: "Assignment 1"
subtitle: "Introduction to Quarto"
author: "Your Group's Names"
date: "January XX, 2023"
format: html
editor: visual
bibliography: "assets/my-bibliography.bib"
csl: "assets/apa-single-spaced.csl"
---</code></pre>
<p>Use of the APA CSL file not only formats the references according to APA format, but it also fixed the order of the citations in the text itself! (Even though we included the Ross citation identifier prior to the Carmichael citation identifier in the multiple references example, the APA CSL file put them in the text alphabetically!)</p>
<p><br></p>
</section>
<section id="citation-extras" class="level3" data-number="3.4.6">
<h3 data-number="3.4.6" class="anchored" data-anchor-id="citation-extras"><span class="header-section-number">3.4.6</span> Citation Extras</h3>
<p>One R package that is extremely useful, especially if you are using the visual editor in RStudio for writing QMD documents, is <code>{citr}</code>. This package provides functionality and an RStudio Add-In to search a BibTeX-file to create and insert formatted Markdown citations into a QMD document.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/02-citr-package.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%" alt="Screenshot of the citr package."></p>
</figure>
</div>
</div>
</div>
<p>The <code>{citr}</code> package is only available via GitHub, so you will need to install it using <code>{remotes}</code> or <code>{devtools}</code>. (See the Computational Toolkit book for a reminder on how to do this.) The directions for installing <code>{citr}</code> are also on the <a href="https://github.com/crsh/citr">citr webpage</a> along with instructions for using the package.</p>
<p><br></p>
</section>
</section>
<section id="auto-populating-the-date-in-your-yaml" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Auto-Populating the Date in Your YAML</h1>
<p>We can auto-populate the <code>date:</code> key in our document’s YAML by including “today”.</p>
<pre><code>---
title: "Assignment 1"
subtitle: "Introduction to Quarto"
author: "Your Group's Names"
date: "today"
format: html
editor: visual
bibliography: "assets/my-bibliography.bib"
---</code></pre>
<p>You can also use an inline code chunk that calls the <code>Sys.Date()</code> function. This function returns your computer’s idea of the current date in the <code>YYYY-MM-DD</code> format (ISO 8601 standard). If you want to be hyper specific, you can use <code>Sys.time()</code> to return the date and time in the format: <code>YYYY-MM-DD HH-MM:SS Time Zone</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Return date</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.Date</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2025-02-10"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Return time</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.time</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2025-02-10 08:40:28 CST"</code></pre>
</div>
</div>
<p>Here is an example of the YAML in the <code>date:</code> key to use <code>Sys.Date()</code> to auto-populate the date.</p>
<pre><code>---
title: "Assignment 1"
subtitle: "Introduction to Quarto"
author: "Your Group's Names"
date: " `r Sys.Date()` "
format: html
editor: visual
bibliography: "assets/my-bibliography.bib"
---</code></pre>
<p>Note that the inline chunk is embedded in quotation marks. We can custom format each of these using the <code>format()</code> function. This function takes the <code>Sys.Date()</code> function as its first argument, and then a character string of formatting rules. Here I format the date to have the full month name, day of the month, and year (with century): e.g., January 12, 2023.</p>
<pre><code>---
title: "Assignment 1"
subtitle: "Introduction to Quarto"
author: "Your Group's Names"
date: " `r format(Sys.Date(), '%B %d %Y')`"
format: html
editor: visual
bibliography: "assets/my-bibliography.bib"
---</code></pre>
<p>You can see all the formatting options by calling <code>help(strptime)</code>.</p>
<p><br></p>
<section id="learn-more" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="learn-more"><span class="header-section-number">4.1</span> Learn More</h2>
<p>Yihui Xie, the creater of the RMarkdown package (which does a lot of the work in converting your QMD file to an HTML/PDF file, gave a nice trechnical talk to the <em>American Statistical Association’s Section on Statistical Computing</em> that explain what actually happens behind the scenes when you click the <code>Knit</code> or <code>Render</code> button in RStudio to render a RMD or QMD document.</p>
<ul>
<li><a href="https://www.youtube.com/watch?v=fiy32LjgGUE">An anatomy of R Markdown with minimal applications</a></li>
</ul>
<p><br></p>
</section>
<section id="references" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="references"><span class="header-section-number">4.2</span> References</h2>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-carmichael_1954" class="csl-entry" role="listitem">
Carmichael, L. (1954). Laziness and the scholarly life. <em>The Scientific Monthly</em>, <em>78</em>(4), 208–213.
</div>
<div id="ref-ross_2020" class="csl-entry" role="listitem">
Ross, C. T., Winterhalder, B., &amp; McElreath, R. (2020). Racial disparities in police use of deadly force against unarmed individuals persist after appropriately benchmarking shooting data on violent crime rates. <em>Social Psychological and Personality Science</em>, 194855062091607. <a href="https://doi.org/10.1177/1948550620916071">https://doi.org/10.1177/1948550620916071</a>
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01-03-introduction-to-quarto.html" class="pagination-link" aria-label="Introduction to Quarto">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Quarto</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./01-05-creating-tables.html" class="pagination-link" aria-label="Creating Tables with gt">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Creating Tables with gt</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb29" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># More Quarto</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"scripts/_common.R"</span>)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>pew <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/zief0002/fluffy-ants/main/data/pew.csv"</span>)</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.1</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> news, <span class="at">data =</span> pew)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>lm1coef <span class="ot">=</span> <span class="fu">tidy</span>(lm<span class="fl">.1</span>)</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>This document contains some additional instruction for EPsy 8252. Note that I might add to this as students hit me with questions over the course of the semester.</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## Code Chunks for Figures</span></span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>Code chunks can be used to do anything you can do in R. For example we can fit regression models, create plots, compute summary measures, or mutate dummy variables into our data. For figures, there are a bunch of chunk options that are useful.</span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>To label code chunks that include figures, we will append <span class="in">`fig-`</span> to the label name. For example, we can use <span class="in">`#| label: fig-density-knowledge`</span> to label a code chunk where we are creating a density plot of the news knowledge variable. </span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-36"><a href="#cb29-36" aria-hidden="true" tabindex="-1"></a>We can add a caption using the <span class="in">`#| fig-cap:`</span> chunk option. It is also a good idea to also include the <span class="in">`#| fig-alt:`</span> chunk option with figures. This provides alternative text for screenreaders (which is required under the new federal accessability laws). Below is an example of this:</span>
<span id="cb29-37"><a href="#cb29-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-38"><a href="#cb29-38" aria-hidden="true" tabindex="-1"></a><span class="in">````         </span></span>
<span id="cb29-39"><a href="#cb29-39" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-40"><a href="#cb29-40" aria-hidden="true" tabindex="-1"></a><span class="in">title: "My First Quarto Document"</span></span>
<span id="cb29-41"><a href="#cb29-41" aria-hidden="true" tabindex="-1"></a><span class="in">subtitle: "Hello World"</span></span>
<span id="cb29-42"><a href="#cb29-42" aria-hidden="true" tabindex="-1"></a><span class="in">author: "Andy and Iggy"</span></span>
<span id="cb29-43"><a href="#cb29-43" aria-hidden="true" tabindex="-1"></a><span class="in">date: today</span></span>
<span id="cb29-44"><a href="#cb29-44" aria-hidden="true" tabindex="-1"></a><span class="in">format: html</span></span>
<span id="cb29-45"><a href="#cb29-45" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-46"><a href="#cb29-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-47"><a href="#cb29-47" aria-hidden="true" tabindex="-1"></a><span class="in"># Code Chunk</span></span>
<span id="cb29-48"><a href="#cb29-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-49"><a href="#cb29-49" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-50"><a href="#cb29-50" aria-hidden="true" tabindex="-1"></a><span class="in">#| label: fig-density-knowledge</span></span>
<span id="cb29-51"><a href="#cb29-51" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-cap: "Here is your figure caption."</span></span>
<span id="cb29-52"><a href="#cb29-52" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-alt: "Here is alternative text for screenreaders."</span></span>
<span id="cb29-53"><a href="#cb29-53" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(data = pew, aes(x = knowledge)) +</span></span>
<span id="cb29-54"><a href="#cb29-54" aria-hidden="true" tabindex="-1"></a><span class="in">   geom_density()</span></span>
<span id="cb29-55"><a href="#cb29-55" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-56"><a href="#cb29-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-57"><a href="#cb29-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-58"><a href="#cb29-58" aria-hidden="true" tabindex="-1"></a><span class="in">````</span></span>
<span id="cb29-59"><a href="#cb29-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-60"><a href="#cb29-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-61"><a href="#cb29-61" aria-hidden="true" tabindex="-1"></a>Notice that by labeling this chunk with <span class="in">`fig-`</span>, the figure is numbered in the document. This allows the figure to also be cross-referenced. You can do this by using the "at" symbol (\@) along with the figure's label name. For example, to cross-reference to the density plot we created, we could use something like:</span>
<span id="cb29-62"><a href="#cb29-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-63"><a href="#cb29-63" aria-hidden="true" tabindex="-1"></a><span class="in">````         </span></span>
<span id="cb29-64"><a href="#cb29-64" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-65"><a href="#cb29-65" aria-hidden="true" tabindex="-1"></a><span class="in">title: "My First Quarto Document"</span></span>
<span id="cb29-66"><a href="#cb29-66" aria-hidden="true" tabindex="-1"></a><span class="in">subtitle: "Hello World"</span></span>
<span id="cb29-67"><a href="#cb29-67" aria-hidden="true" tabindex="-1"></a><span class="in">author: "Andy and Iggy"</span></span>
<span id="cb29-68"><a href="#cb29-68" aria-hidden="true" tabindex="-1"></a><span class="in">date: today</span></span>
<span id="cb29-69"><a href="#cb29-69" aria-hidden="true" tabindex="-1"></a><span class="in">format: html</span></span>
<span id="cb29-70"><a href="#cb29-70" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-71"><a href="#cb29-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-72"><a href="#cb29-72" aria-hidden="true" tabindex="-1"></a><span class="in"># Code Chunk</span></span>
<span id="cb29-73"><a href="#cb29-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-74"><a href="#cb29-74" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-75"><a href="#cb29-75" aria-hidden="true" tabindex="-1"></a><span class="in">#| label: fig-density-knowledge</span></span>
<span id="cb29-76"><a href="#cb29-76" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-cap: "Here is your figure caption."</span></span>
<span id="cb29-77"><a href="#cb29-77" aria-hidden="true" tabindex="-1"></a><span class="in">#| fig-alt: "Here is alternative text for screenreaders."</span></span>
<span id="cb29-78"><a href="#cb29-78" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(data = pew, aes(x = knowledge)) +</span></span>
<span id="cb29-79"><a href="#cb29-79" aria-hidden="true" tabindex="-1"></a><span class="in">   geom_density()</span></span>
<span id="cb29-80"><a href="#cb29-80" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-81"><a href="#cb29-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-82"><a href="#cb29-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-83"><a href="#cb29-83" aria-hidden="true" tabindex="-1"></a><span class="in">The distribution of news knowledge is unimodal (see @fig-density-knowledge).</span></span>
<span id="cb29-84"><a href="#cb29-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-85"><a href="#cb29-85" aria-hidden="true" tabindex="-1"></a><span class="in">````</span></span>
<span id="cb29-86"><a href="#cb29-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-87"><a href="#cb29-87" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-88"><a href="#cb29-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-89"><a href="#cb29-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-90"><a href="#cb29-90" aria-hidden="true" tabindex="-1"></a><span class="fu">### Figure Size</span></span>
<span id="cb29-91"><a href="#cb29-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-92"><a href="#cb29-92" aria-hidden="true" tabindex="-1"></a>There are a couple other chunk options for figures that help set the aspect ratio and size of the figure in your document. The aspect ratio is the ratio of a figure's width to its height. We set this using the <span class="in">`#| fig-width:`</span> and <span class="in">`#| fig-height:`</span> chunk options. (The default value for both is 6; thus the figure appears square.) Below we change these so that the figure appears wider than it is tall.</span>
<span id="cb29-93"><a href="#cb29-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-96"><a href="#cb29-96" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-97"><a href="#cb29-97" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: fenced</span></span>
<span id="cb29-98"><a href="#cb29-98" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-density-knowledge-2</span></span>
<span id="cb29-99"><a href="#cb29-99" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Density plot showing the distribution of news knowledge."</span></span>
<span id="cb29-100"><a href="#cb29-100" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Density plot showing a a unimodal distribution of news knowledge."</span></span>
<span id="cb29-101"><a href="#cb29-101" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 9</span></span>
<span id="cb29-102"><a href="#cb29-102" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb29-103"><a href="#cb29-103" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> pew, <span class="fu">aes</span>(<span class="at">x =</span> knowledge)) <span class="sc">+</span></span>
<span id="cb29-104"><a href="#cb29-104" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_density</span>()</span>
<span id="cb29-105"><a href="#cb29-105" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-106"><a href="#cb29-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-107"><a href="#cb29-107" aria-hidden="true" tabindex="-1"></a>::: fyi</span>
<span id="cb29-108"><a href="#cb29-108" aria-hidden="true" tabindex="-1"></a>**FYI**</span>
<span id="cb29-109"><a href="#cb29-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-110"><a href="#cb29-110" aria-hidden="true" tabindex="-1"></a>It is important to change the aspect ratio when you have legends or when you are using <span class="in">`{patchwork}`</span> to stack or put multiple figures next to each other. Many times you need to find a good aspect ratio though trial-and-error of trying different values.</span>
<span id="cb29-111"><a href="#cb29-111" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb29-112"><a href="#cb29-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-113"><a href="#cb29-113" aria-hidden="true" tabindex="-1"></a>The actual size of the figure in the document is independent of the aspect ratio and can be set using the <span class="in">`#| out-width:`</span> or <span class="in">`#| out-height:`</span> chunk option. These options take a character string of the direct size (in HTML documents this is typically in pixels) or of the percentage of the output width/height. Here we keep the same aspect ratio, but make the figure smaller by setting the figure width to 40% of the document's width.</span>
<span id="cb29-114"><a href="#cb29-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-117"><a href="#cb29-117" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-118"><a href="#cb29-118" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: fenced</span></span>
<span id="cb29-119"><a href="#cb29-119" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-density-knowledge-3</span></span>
<span id="cb29-120"><a href="#cb29-120" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Density plot showing the distribution of news knowledge."</span></span>
<span id="cb29-121"><a href="#cb29-121" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Density plot showing a a unimodal distribution of news knowledge."</span></span>
<span id="cb29-122"><a href="#cb29-122" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "40%"</span></span>
<span id="cb29-123"><a href="#cb29-123" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> pew, <span class="fu">aes</span>(<span class="at">x =</span> news, <span class="at">y =</span> knowledge)) <span class="sc">+</span></span>
<span id="cb29-124"><a href="#cb29-124" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_point</span>()</span>
<span id="cb29-125"><a href="#cb29-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-126"><a href="#cb29-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-127"><a href="#cb29-127" aria-hidden="true" tabindex="-1"></a>::: fyi</span>
<span id="cb29-128"><a href="#cb29-128" aria-hidden="true" tabindex="-1"></a>**PROTIP**</span>
<span id="cb29-129"><a href="#cb29-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-130"><a href="#cb29-130" aria-hidden="true" tabindex="-1"></a>If you set the aspect ratio of the figure, you need only set <span class="in">`#| out-width:`</span> or <span class="in">`#| out-height:`</span>. You don't need to set both as the other will be determined by the aspect ratio.</span>
<span id="cb29-131"><a href="#cb29-131" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb29-132"><a href="#cb29-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-133"><a href="#cb29-133" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-134"><a href="#cb29-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-135"><a href="#cb29-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-136"><a href="#cb29-136" aria-hidden="true" tabindex="-1"></a><span class="fu">## Inline Code Chunks for Better Reproducibility</span></span>
<span id="cb29-137"><a href="#cb29-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-138"><a href="#cb29-138" aria-hidden="true" tabindex="-1"></a>In writing papers where there are results from data analyses being reported in the text, inline code chunks are boss! For example, consider writing the following sentence in an analysis of the *pew.csv* data.</span>
<span id="cb29-139"><a href="#cb29-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-140"><a href="#cb29-140" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; The effect of news exposure on news knowledge is 0.327 (SE = 0.09).</span></span>
<span id="cb29-141"><a href="#cb29-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-142"><a href="#cb29-142" aria-hidden="true" tabindex="-1"></a>Rather than computing these values and then transposing the values into the sentence, we can use inline code chunks to directly compute and write the values in the sentence. Recall, earlier we assigned the <span class="in">`tidy()`</span> output into an object called <span class="in">`lm1coef`</span>. The results from <span class="in">`tidy()`</span> are a tibble (or data frame).</span>
<span id="cb29-143"><a href="#cb29-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-146"><a href="#cb29-146" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-147"><a href="#cb29-147" aria-hidden="true" tabindex="-1"></a><span class="co"># Print output</span></span>
<span id="cb29-148"><a href="#cb29-148" aria-hidden="true" tabindex="-1"></a>lm1coef</span>
<span id="cb29-149"><a href="#cb29-149" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-150"><a href="#cb29-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-151"><a href="#cb29-151" aria-hidden="true" tabindex="-1"></a>A tibble/data frame is a combination of rows and columns. We can access different parts of the tibble by indexing the row and column that we want. For example, to access the slope standard error, which is in the 2nd row and 3rd column, we could use:</span>
<span id="cb29-152"><a href="#cb29-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-155"><a href="#cb29-155" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-156"><a href="#cb29-156" aria-hidden="true" tabindex="-1"></a><span class="co"># Access slope SE</span></span>
<span id="cb29-157"><a href="#cb29-157" aria-hidden="true" tabindex="-1"></a>lm1coef[<span class="dv">2</span>, <span class="dv">3</span>]</span>
<span id="cb29-158"><a href="#cb29-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-159"><a href="#cb29-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-160"><a href="#cb29-160" aria-hidden="true" tabindex="-1"></a>Unfortunately, this also comes out as a labelled tibble. If we just want the SE value we double index this. Thus to get the value of the slope SE, we use:</span>
<span id="cb29-161"><a href="#cb29-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-164"><a href="#cb29-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-165"><a href="#cb29-165" aria-hidden="true" tabindex="-1"></a><span class="co"># Access slope SE number only</span></span>
<span id="cb29-166"><a href="#cb29-166" aria-hidden="true" tabindex="-1"></a>lm1coef[[<span class="dv">2</span>, <span class="dv">3</span>]]</span>
<span id="cb29-167"><a href="#cb29-167" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-168"><a href="#cb29-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-169"><a href="#cb29-169" aria-hidden="true" tabindex="-1"></a>Here is how we could extract the slope value and the SE of the slope value to write our earlier sentence:</span>
<span id="cb29-170"><a href="#cb29-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-171"><a href="#cb29-171" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; The effect of news exposure on news knowledge is `</span><span class="in">` `</span><span class="at">r knitr::inline_expr("lm1coef[</span><span class="co">[</span><span class="ot">2, 2</span><span class="co">]</span><span class="at">]")` `` (SE = `</span><span class="in">` `</span><span class="at">r knitr::inline_expr("lm1coef[</span><span class="co">[</span><span class="ot">2, 3</span><span class="co">]</span><span class="at">]")` ``).</span></span>
<span id="cb29-172"><a href="#cb29-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-173"><a href="#cb29-173" aria-hidden="true" tabindex="-1"></a>This produces the following sentence in the rendered document:</span>
<span id="cb29-174"><a href="#cb29-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-175"><a href="#cb29-175" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; The effect of news exposure on news knowledge is </span><span class="in">`r lm1coef[[2, 2]]`</span><span class="at"> (SE = </span><span class="in">`r lm1coef[[2, 3]]`</span><span class="at">).</span></span>
<span id="cb29-176"><a href="#cb29-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-177"><a href="#cb29-177" aria-hidden="true" tabindex="-1"></a>Note: You don't need to assign the output to an object to index it. For example, the SE could also be extracted using: `<span class="in">` `</span>r knitr::inline_expr("tidy(lm.1)[<span class="co">[</span><span class="ot">2, 2</span><span class="co">]</span>]")` ``</span>
<span id="cb29-178"><a href="#cb29-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-179"><a href="#cb29-179" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-180"><a href="#cb29-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-181"><a href="#cb29-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-182"><a href="#cb29-182" aria-hidden="true" tabindex="-1"></a><span class="fu">### Rounding</span></span>
<span id="cb29-183"><a href="#cb29-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-184"><a href="#cb29-184" aria-hidden="true" tabindex="-1"></a>There are several ways to set the rounding to two decimal places. One is to embed the computation in the <span class="in">`round()`</span> function. For example, in the first inline chunk we could use: <span class="in">`round(lm1coef[[2, 3]], 2)`</span>.</span>
<span id="cb29-185"><a href="#cb29-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-186"><a href="#cb29-186" aria-hidden="true" tabindex="-1"></a>You can also do this in a separate code chunk and then call the values in the inline computation (as suggested in the <span class="co">[</span><span class="ot">Quarto Computations Tutorial</span><span class="co">](https://quarto.org/docs/get-started/computations/rstudio.html)</span>).</span>
<span id="cb29-187"><a href="#cb29-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-188"><a href="#cb29-188" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-189"><a href="#cb29-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-190"><a href="#cb29-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-191"><a href="#cb29-191" aria-hidden="true" tabindex="-1"></a><span class="fu">## Multiline Equations</span></span>
<span id="cb29-192"><a href="#cb29-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-193"><a href="#cb29-193" aria-hidden="true" tabindex="-1"></a>There are a couple of ways to create multiline equations in a Quarto document. I tend to use the <span class="in">`split`</span> environment from LaTeX to do this. To use this:</span>
<span id="cb29-194"><a href="#cb29-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-195"><a href="#cb29-195" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Include <span class="in">`\begin{split}`</span> and <span class="in">`\end{split}`</span> in the display equation.</span>
<span id="cb29-196"><a href="#cb29-196" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>At the end of each line (where you want a linebreak) include a double backslash, <span class="in">`\\`</span>.</span>
<span id="cb29-197"><a href="#cb29-197" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>In each line of the multiline equation, also include the ampersand sign (<span class="in">`&amp;`</span>) at the point we want the multiple lines to align vertically.</span>
<span id="cb29-198"><a href="#cb29-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-199"><a href="#cb29-199" aria-hidden="true" tabindex="-1"></a>Here is an example:</span>
<span id="cb29-200"><a href="#cb29-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-201"><a href="#cb29-201" aria-hidden="true" tabindex="-1"></a><span class="in">```         </span></span>
<span id="cb29-202"><a href="#cb29-202" aria-hidden="true" tabindex="-1"></a><span class="in">$$</span></span>
<span id="cb29-203"><a href="#cb29-203" aria-hidden="true" tabindex="-1"></a><span class="in">\begin{split}</span></span>
<span id="cb29-204"><a href="#cb29-204" aria-hidden="true" tabindex="-1"></a><span class="in">\hat{y}_i &amp;= 3 + 4(1) \\</span></span>
<span id="cb29-205"><a href="#cb29-205" aria-hidden="true" tabindex="-1"></a><span class="in">&amp;= 7</span></span>
<span id="cb29-206"><a href="#cb29-206" aria-hidden="true" tabindex="-1"></a><span class="in">\end{split}</span></span>
<span id="cb29-207"><a href="#cb29-207" aria-hidden="true" tabindex="-1"></a><span class="in">$$</span></span>
<span id="cb29-208"><a href="#cb29-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-209"><a href="#cb29-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-210"><a href="#cb29-210" aria-hidden="true" tabindex="-1"></a>And the resulting display equation is:</span>
<span id="cb29-211"><a href="#cb29-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-212"><a href="#cb29-212" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb29-213"><a href="#cb29-213" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb29-214"><a href="#cb29-214" aria-hidden="true" tabindex="-1"></a>\hat{y}_i &amp;= 3 + 4(1) <span class="sc">\\</span></span>
<span id="cb29-215"><a href="#cb29-215" aria-hidden="true" tabindex="-1"></a>&amp;= 7</span>
<span id="cb29-216"><a href="#cb29-216" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb29-217"><a href="#cb29-217" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb29-218"><a href="#cb29-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-219"><a href="#cb29-219" aria-hidden="true" tabindex="-1"></a>Note that the ampersand appeared immediately before the equal sign in each line of the equation, so that is where the two lines are aligned vertically (the equal signs are on top of each other). You can add as many lines to this as you want.</span>
<span id="cb29-220"><a href="#cb29-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-221"><a href="#cb29-221" aria-hidden="true" tabindex="-1"></a>::: fyi</span>
<span id="cb29-222"><a href="#cb29-222" aria-hidden="true" tabindex="-1"></a>**FYI**</span>
<span id="cb29-223"><a href="#cb29-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-224"><a href="#cb29-224" aria-hidden="true" tabindex="-1"></a>Multiline equations are quite useful to show your work and when you have really long single equations that need to be broken up so they fit on the page (e.g., a regression equation with many predictors).</span>
<span id="cb29-225"><a href="#cb29-225" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb29-226"><a href="#cb29-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-227"><a href="#cb29-227" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-228"><a href="#cb29-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-229"><a href="#cb29-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-230"><a href="#cb29-230" aria-hidden="true" tabindex="-1"></a><span class="fu">### Spacing Out the Lines</span></span>
<span id="cb29-231"><a href="#cb29-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-232"><a href="#cb29-232" aria-hidden="true" tabindex="-1"></a>You can add space between the lines of your multiline equation by including a unit of measurement between square brackets after the double backslashes.</span>
<span id="cb29-233"><a href="#cb29-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-234"><a href="#cb29-234" aria-hidden="true" tabindex="-1"></a><span class="in">```         </span></span>
<span id="cb29-235"><a href="#cb29-235" aria-hidden="true" tabindex="-1"></a><span class="in">$$</span></span>
<span id="cb29-236"><a href="#cb29-236" aria-hidden="true" tabindex="-1"></a><span class="in">\begin{split}</span></span>
<span id="cb29-237"><a href="#cb29-237" aria-hidden="true" tabindex="-1"></a><span class="in">\hat{y}_i &amp;= 3 + 4(1) \\[1em]</span></span>
<span id="cb29-238"><a href="#cb29-238" aria-hidden="true" tabindex="-1"></a><span class="in">&amp;= 7</span></span>
<span id="cb29-239"><a href="#cb29-239" aria-hidden="true" tabindex="-1"></a><span class="in">\end{split}</span></span>
<span id="cb29-240"><a href="#cb29-240" aria-hidden="true" tabindex="-1"></a><span class="in">$$</span></span>
<span id="cb29-241"><a href="#cb29-241" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-242"><a href="#cb29-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-243"><a href="#cb29-243" aria-hidden="true" tabindex="-1"></a>Here the resulting display equation is:</span>
<span id="cb29-244"><a href="#cb29-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-245"><a href="#cb29-245" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb29-246"><a href="#cb29-246" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb29-247"><a href="#cb29-247" aria-hidden="true" tabindex="-1"></a>\hat{y}_i &amp;= 3 + 4(1) <span class="sc">\\</span><span class="co">[</span><span class="ot">1em</span><span class="co">]</span></span>
<span id="cb29-248"><a href="#cb29-248" aria-hidden="true" tabindex="-1"></a>&amp;= 7</span>
<span id="cb29-249"><a href="#cb29-249" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb29-250"><a href="#cb29-250" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb29-251"><a href="#cb29-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-252"><a href="#cb29-252" aria-hidden="true" tabindex="-1"></a>Here we have added line space of 1 em. An *em* is a unit for measuring the width of printed work, equal to the height of the type size being used (typically the width of the letter "m"). Other common printing units include the *en* (the width of the letter "n"), and the *ex* (the width of the letter "x").</span>
<span id="cb29-253"><a href="#cb29-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-254"><a href="#cb29-254" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- ::: fyi --&gt;</span></span>
<span id="cb29-255"><a href="#cb29-255" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- Question #8 on the assignment actually asks: --&gt;</span></span>
<span id="cb29-256"><a href="#cb29-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-257"><a href="#cb29-257" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- &gt; Use a display equation to write the equation for the underlying regression model (including error and assumptions) using Greek letters, subscripts, and variable names. Also write the equation for the fitted least squares regression equation based on the output from `lm()`. Type these two equations in the same display equation, each on a separate line of text in your document, and align the equals signs. --&gt;</span></span>
<span id="cb29-258"><a href="#cb29-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-259"><a href="#cb29-259" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- Try writing this multiline equation. --&gt;</span></span>
<span id="cb29-260"><a href="#cb29-260" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- ::: --&gt;</span></span>
<span id="cb29-261"><a href="#cb29-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-262"><a href="#cb29-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-263"><a href="#cb29-263" aria-hidden="true" tabindex="-1"></a>:::fyi</span>
<span id="cb29-264"><a href="#cb29-264" aria-hidden="true" tabindex="-1"></a><span class="fu">### Typesetting 101: Hyphens, Minus Signs, and Dashes</span></span>
<span id="cb29-265"><a href="#cb29-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-266"><a href="#cb29-266" aria-hidden="true" tabindex="-1"></a>In printed work the width of a hyphen, a minus sign, and dashes are all different. Quarto will correctly typeset these, but you have to indicate what you want. Below are how we indicate these in Quarto.</span>
<span id="cb29-267"><a href="#cb29-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-268"><a href="#cb29-268" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Hyphen:** A hyphen is used to join two or more words together. To typeset a hyphen in Quarto, use a single hyphen; <span class="in">`-`</span>.</span>
<span id="cb29-269"><a href="#cb29-269" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**En Dash:** An en dash is used to mark ranges and to indicate the meaning "to" in phrases like "Minneapolis--St. Paul". An en dash is slightly longer than a hyphen and is typeset in Quarto using two hyphens; <span class="in">`--`</span>.</span>
<span id="cb29-270"><a href="#cb29-270" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Em Dash:** An em dash is used to separate extra information or mark a break in a sentence. An em dash is slightly longer than an en dash and is typeset in Quarto using three hyphens; <span class="in">`---`</span>.</span>
<span id="cb29-271"><a href="#cb29-271" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Minus Sign:** A minus sign is used in mathematical expressions (e.g., in subtraction or to indicate a negative number). To typeset a minus sign, use the inline equation with a single hyphen; <span class="in">`$-$`</span>. When a minus sign is typeset, not only is the length of it different than a hyphen, but it also includes the correct spacing around it for mathematical typesetting.</span>
<span id="cb29-272"><a href="#cb29-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-273"><a href="#cb29-273" aria-hidden="true" tabindex="-1"></a>Here is a sentence incorporating each of these so you can see the differences:</span>
<span id="cb29-274"><a href="#cb29-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-275"><a href="#cb29-275" aria-hidden="true" tabindex="-1"></a>*During the time from January--February, my three dogs enjoy playing in the snow---apparently snow is fun for canines---with their sweaters on since it is* $-30$-degrees Fahrenheit outside.</span>
<span id="cb29-276"><a href="#cb29-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-277"><a href="#cb29-277" aria-hidden="true" tabindex="-1"></a>The input for this sentence was:</span>
<span id="cb29-278"><a href="#cb29-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-279"><a href="#cb29-279" aria-hidden="true" tabindex="-1"></a><span class="in">`During the time from January--February, my three dogs enjoy playing in the snow---apparently snow is fun for canines---with their sweaters on since it is $-30$-degrees Fahrenheit outside.`</span></span>
<span id="cb29-280"><a href="#cb29-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-281"><a href="#cb29-281" aria-hidden="true" tabindex="-1"></a>Note that you can also typeset these in Word:</span>
<span id="cb29-282"><a href="#cb29-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-283"><a href="#cb29-283" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Hyphen:** On both a Mac and PC, press "hyphen".</span>
<span id="cb29-284"><a href="#cb29-284" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**En Dash:** On a Mac, press "option+hyphen key". On a PC, press "ctrl+hyphen".</span>
<span id="cb29-285"><a href="#cb29-285" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Em Dash:** On a Mac, press "option+shift+hyphen key". On a PC, press "alt+ctrl+hyphen".</span>
<span id="cb29-286"><a href="#cb29-286" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Minus Sign:** For a minus sign, you should use Equation Editor.</span>
<span id="cb29-287"><a href="#cb29-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-288"><a href="#cb29-288" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb29-289"><a href="#cb29-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-290"><a href="#cb29-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-291"><a href="#cb29-291" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-292"><a href="#cb29-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-293"><a href="#cb29-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-294"><a href="#cb29-294" aria-hidden="true" tabindex="-1"></a><span class="fu">## Citations</span></span>
<span id="cb29-295"><a href="#cb29-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-296"><a href="#cb29-296" aria-hidden="true" tabindex="-1"></a>To add citations, we need to:</span>
<span id="cb29-297"><a href="#cb29-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-298"><a href="#cb29-298" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Create a BibTeX (.bib) file that holds the metadata for our references.</span>
<span id="cb29-299"><a href="#cb29-299" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Save the BibTeX file to our project directory (typically in the <span class="in">`assets`</span> directory)</span>
<span id="cb29-300"><a href="#cb29-300" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Include <span class="in">`bibliography: "location/bibliography-name.bib"`</span> in the YAML of our QMD document</span>
<span id="cb29-301"><a href="#cb29-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-302"><a href="#cb29-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-303"><a href="#cb29-303" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-304"><a href="#cb29-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-305"><a href="#cb29-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-306"><a href="#cb29-306" aria-hidden="true" tabindex="-1"></a><span class="fu">### Creating .bib Files Using Zotero</span></span>
<span id="cb29-307"><a href="#cb29-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-308"><a href="#cb29-308" aria-hidden="true" tabindex="-1"></a>Most reference managers (e.g., Papers, Zotero, Mendelay) can produce BibTex files. Here I will illustrate the process using Zotero.</span>
<span id="cb29-309"><a href="#cb29-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-310"><a href="#cb29-310" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Create a <span class="in">`New Collection`</span>.</span>
<span id="cb29-311"><a href="#cb29-311" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Drag the references you want in your BibTeX database into this collection. For today, drag the @carmichael_1954 and @ross_2020 references into this collection.</span>
<span id="cb29-312"><a href="#cb29-312" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Right-click the collection and select <span class="in">`Export Collection`</span>.</span>
<span id="cb29-313"><a href="#cb29-313" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>In the pop-up window, change the format of the exported collection to <span class="in">`BibTex`</span>.</span>
<span id="cb29-314"><a href="#cb29-314" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Click <span class="in">`OK`</span>.</span>
<span id="cb29-315"><a href="#cb29-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-316"><a href="#cb29-316" aria-hidden="true" tabindex="-1"></a>Name the BibTex file (here I named it <span class="in">`my-bibliography.bib`</span>) and save it in the <span class="in">`assets`</span> folder. </span>
<span id="cb29-317"><a href="#cb29-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-318"><a href="#cb29-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-321"><a href="#cb29-321" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-322"><a href="#cb29-322" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb29-323"><a href="#cb29-323" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "90%"</span></span>
<span id="cb29-324"><a href="#cb29-324" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Zotero screenshot showing exporting of BibTeX file."</span></span>
<span id="cb29-325"><a href="#cb29-325" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figs/02-zotero-bibtex.png"</span>)</span>
<span id="cb29-326"><a href="#cb29-326" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-327"><a href="#cb29-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-328"><a href="#cb29-328" aria-hidden="true" tabindex="-1"></a>When you call the BibTex file in the <span class="in">`bibliography:`</span> key of the YAML in your QMD document, you will need to give the location of the BibTex (relative to the QMD document) and the name you just gave it. For example if you are calling a bibliography in the quarto document <span class="in">`assignment-01.qmd`</span> that has the following directory/folder structure:</span>
<span id="cb29-329"><a href="#cb29-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-330"><a href="#cb29-330" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-331"><a href="#cb29-331" aria-hidden="true" tabindex="-1"></a><span class="in">assignment-01</span></span>
<span id="cb29-332"><a href="#cb29-332" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── README</span></span>
<span id="cb29-333"><a href="#cb29-333" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── assets</span></span>
<span id="cb29-334"><a href="#cb29-334" aria-hidden="true" tabindex="-1"></a><span class="in">       └── my-bibliography.bib</span></span>
<span id="cb29-335"><a href="#cb29-335" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── assignment-01.qmd</span></span>
<span id="cb29-336"><a href="#cb29-336" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── assignment-01.Rproj</span></span>
<span id="cb29-337"><a href="#cb29-337" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── data</span></span>
<span id="cb29-338"><a href="#cb29-338" aria-hidden="true" tabindex="-1"></a><span class="in">       └── fertility.csv</span></span>
<span id="cb29-339"><a href="#cb29-339" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── figs</span></span>
<span id="cb29-340"><a href="#cb29-340" aria-hidden="true" tabindex="-1"></a><span class="in">    └── scripts</span></span>
<span id="cb29-341"><a href="#cb29-341" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-342"><a href="#cb29-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-343"><a href="#cb29-343" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-344"><a href="#cb29-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-345"><a href="#cb29-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-346"><a href="#cb29-346" aria-hidden="true" tabindex="-1"></a><span class="fu">### Including the BIB File in your YAML</span></span>
<span id="cb29-347"><a href="#cb29-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-348"><a href="#cb29-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-349"><a href="#cb29-349" aria-hidden="true" tabindex="-1"></a>You would then include the following in your Quarto document's YAML:</span>
<span id="cb29-350"><a href="#cb29-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-351"><a href="#cb29-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-352"><a href="#cb29-352" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-353"><a href="#cb29-353" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-354"><a href="#cb29-354" aria-hidden="true" tabindex="-1"></a><span class="in">title: "Assignment 1"</span></span>
<span id="cb29-355"><a href="#cb29-355" aria-hidden="true" tabindex="-1"></a><span class="in">subtitle: "Introduction to Quarto"</span></span>
<span id="cb29-356"><a href="#cb29-356" aria-hidden="true" tabindex="-1"></a><span class="in">author: "Your Group's Names"</span></span>
<span id="cb29-357"><a href="#cb29-357" aria-hidden="true" tabindex="-1"></a><span class="in">date: "January XX, 2023"</span></span>
<span id="cb29-358"><a href="#cb29-358" aria-hidden="true" tabindex="-1"></a><span class="in">format: html</span></span>
<span id="cb29-359"><a href="#cb29-359" aria-hidden="true" tabindex="-1"></a><span class="in">editor: visual</span></span>
<span id="cb29-360"><a href="#cb29-360" aria-hidden="true" tabindex="-1"></a><span class="in">bibliography: "assets/my-bibliography.bib"</span></span>
<span id="cb29-361"><a href="#cb29-361" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-362"><a href="#cb29-362" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-363"><a href="#cb29-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-364"><a href="#cb29-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-365"><a href="#cb29-365" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-366"><a href="#cb29-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-367"><a href="#cb29-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-368"><a href="#cb29-368" aria-hidden="true" tabindex="-1"></a><span class="fu">### BibTex Files</span></span>
<span id="cb29-369"><a href="#cb29-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-370"><a href="#cb29-370" aria-hidden="true" tabindex="-1"></a>BibTeX files are essentially databases that store bibliographic information in a plain-text (style-independent) file. The database includes a set of references and their metadata. Here is the raw text inside an example BibTex file that includes two articles written by @carmichael_1954 and @ross_2020.</span>
<span id="cb29-371"><a href="#cb29-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-372"><a href="#cb29-372" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-373"><a href="#cb29-373" aria-hidden="true" tabindex="-1"></a><span class="in">@article{carmichael_1954,</span></span>
<span id="cb29-374"><a href="#cb29-374" aria-hidden="true" tabindex="-1"></a><span class="in">    title = {Laziness and the Scholarly Life},</span></span>
<span id="cb29-375"><a href="#cb29-375" aria-hidden="true" tabindex="-1"></a><span class="in">    volume = {78},</span></span>
<span id="cb29-376"><a href="#cb29-376" aria-hidden="true" tabindex="-1"></a><span class="in">    number = {4},</span></span>
<span id="cb29-377"><a href="#cb29-377" aria-hidden="true" tabindex="-1"></a><span class="in">    journal = {The Scientific Monthly},</span></span>
<span id="cb29-378"><a href="#cb29-378" aria-hidden="true" tabindex="-1"></a><span class="in">    author = {Carmichael, Leonard},</span></span>
<span id="cb29-379"><a href="#cb29-379" aria-hidden="true" tabindex="-1"></a><span class="in">    year = {1954},</span></span>
<span id="cb29-380"><a href="#cb29-380" aria-hidden="true" tabindex="-1"></a><span class="in">    pages = {208--213}</span></span>
<span id="cb29-381"><a href="#cb29-381" aria-hidden="true" tabindex="-1"></a><span class="in">}</span></span>
<span id="cb29-382"><a href="#cb29-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-383"><a href="#cb29-383" aria-hidden="true" tabindex="-1"></a><span class="in">@article{ross_2020,</span></span>
<span id="cb29-384"><a href="#cb29-384" aria-hidden="true" tabindex="-1"></a><span class="in">    title = {Racial disparities in police use of deadly force against unarmed individuals persist after appropriately benchmarking shooting data on violent crime rates},</span></span>
<span id="cb29-385"><a href="#cb29-385" aria-hidden="true" tabindex="-1"></a><span class="in">    issn = {1948-5506, 1948-5514},</span></span>
<span id="cb29-386"><a href="#cb29-386" aria-hidden="true" tabindex="-1"></a><span class="in">    url = {http://journals.sagepub.com/doi/10.1177/1948550620916071},</span></span>
<span id="cb29-387"><a href="#cb29-387" aria-hidden="true" tabindex="-1"></a><span class="in">    doi = {10.1177/1948550620916071},</span></span>
<span id="cb29-388"><a href="#cb29-388" aria-hidden="true" tabindex="-1"></a><span class="in">    language = {en},</span></span>
<span id="cb29-389"><a href="#cb29-389" aria-hidden="true" tabindex="-1"></a><span class="in">    urldate = {2020-06-24},</span></span>
<span id="cb29-390"><a href="#cb29-390" aria-hidden="true" tabindex="-1"></a><span class="in">    journal = {Social Psychological and Personality Science},</span></span>
<span id="cb29-391"><a href="#cb29-391" aria-hidden="true" tabindex="-1"></a><span class="in">    author = {Ross, Cody T. and Winterhalder, Bruce and McElreath, Richard},</span></span>
<span id="cb29-392"><a href="#cb29-392" aria-hidden="true" tabindex="-1"></a><span class="in">    month = jun,</span></span>
<span id="cb29-393"><a href="#cb29-393" aria-hidden="true" tabindex="-1"></a><span class="in">    year = {2020},</span></span>
<span id="cb29-394"><a href="#cb29-394" aria-hidden="true" tabindex="-1"></a><span class="in">    pages = {194855062091607}</span></span>
<span id="cb29-395"><a href="#cb29-395" aria-hidden="true" tabindex="-1"></a><span class="in">}</span></span>
<span id="cb29-396"><a href="#cb29-396" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-397"><a href="#cb29-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-398"><a href="#cb29-398" aria-hidden="true" tabindex="-1"></a>The citation identifiers in this example are <span class="in">`carmichael_1954`</span> and <span class="in">`ross_2020`</span>. These identifiers are the first bit of text after the initial curly brace in the reference. This is how we will refer to the citations in our QMD document. (Typically these are auto-generated from our reference manager.) To determine the citiation identifiers, you can open your BibTeX file in RStudio. (Do this by using <span class="in">`Open File...`</span> within RStudio; double-clicking on the BibTeX file will likely open it in a different application.)</span>
<span id="cb29-399"><a href="#cb29-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-400"><a href="#cb29-400" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-401"><a href="#cb29-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-402"><a href="#cb29-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-403"><a href="#cb29-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-404"><a href="#cb29-404" aria-hidden="true" tabindex="-1"></a><span class="fu">### Including Citations in Your Quarto Document</span></span>
<span id="cb29-405"><a href="#cb29-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-406"><a href="#cb29-406" aria-hidden="true" tabindex="-1"></a>Citations go inside square brackets and are separated by semicolons. Each citation must have a key, composed of <span class="in">`@citation_identifier`</span> from the database (no spaces between them). For example to cite the Carmichael article:</span>
<span id="cb29-407"><a href="#cb29-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-408"><a href="#cb29-408" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-409"><a href="#cb29-409" aria-hidden="true" tabindex="-1"></a><span class="in">Here is some text and a citation [@carmichael_1954].</span></span>
<span id="cb29-410"><a href="#cb29-410" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-411"><a href="#cb29-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-412"><a href="#cb29-412" aria-hidden="true" tabindex="-1"></a>This will create a citation where you included it in the text and also add the reference at the end of the document. If you want a section header for your references, include a level-1 heading called "References" at the end of your document.</span>
<span id="cb29-413"><a href="#cb29-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-414"><a href="#cb29-414" aria-hidden="true" tabindex="-1"></a>The rendered document now includes a citation where you added this is the QMD document. The associated reference is also included at the end of the document.</span>
<span id="cb29-415"><a href="#cb29-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-418"><a href="#cb29-418" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-419"><a href="#cb29-419" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb29-420"><a href="#cb29-420" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "90%"</span></span>
<span id="cb29-421"><a href="#cb29-421" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Screenshot of rendered Quarto document with citation."</span></span>
<span id="cb29-422"><a href="#cb29-422" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figs/02-citations-01.png"</span>)</span>
<span id="cb29-423"><a href="#cb29-423" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-424"><a href="#cb29-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-425"><a href="#cb29-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-426"><a href="#cb29-426" aria-hidden="true" tabindex="-1"></a>Citations may also include. additional text before and after the citation. In this example we have prefixed the citation with the word "see" and added a page number after the citation. The citation identifier and the text following the citation identifier are separated by a comma.</span>
<span id="cb29-427"><a href="#cb29-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-428"><a href="#cb29-428" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-429"><a href="#cb29-429" aria-hidden="true" tabindex="-1"></a><span class="in">Here is some text and a citation [see @carmichael_1954, p. 208].</span></span>
<span id="cb29-430"><a href="#cb29-430" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-431"><a href="#cb29-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-432"><a href="#cb29-432" aria-hidden="true" tabindex="-1"></a>The output of this is:</span>
<span id="cb29-433"><a href="#cb29-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-434"><a href="#cb29-434" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Here is some text and a citation </span><span class="co">[</span><span class="ot">see @carmichael_1954, p. 208</span><span class="co">]</span><span class="at">.</span></span>
<span id="cb29-435"><a href="#cb29-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-436"><a href="#cb29-436" aria-hidden="true" tabindex="-1"></a>You can also include multiple citations. To do this we include the different citation identifiers separated by a semicolon.</span>
<span id="cb29-437"><a href="#cb29-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-438"><a href="#cb29-438" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-439"><a href="#cb29-439" aria-hidden="true" tabindex="-1"></a><span class="in">Here are multiple citations [@ross_2020; @carmichael_1954].</span></span>
<span id="cb29-440"><a href="#cb29-440" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-441"><a href="#cb29-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-442"><a href="#cb29-442" aria-hidden="true" tabindex="-1"></a>The output of this is:</span>
<span id="cb29-443"><a href="#cb29-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-444"><a href="#cb29-444" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Here are multiple citations </span><span class="co">[</span><span class="ot">@ross_2020; @carmichael_1954</span><span class="co">]</span><span class="at">.</span></span>
<span id="cb29-445"><a href="#cb29-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-446"><a href="#cb29-446" aria-hidden="true" tabindex="-1"></a>We can also change the format of the citation. For example, here we use a format common to starting a sentence with a citation. To do that we omit the square brackets.</span>
<span id="cb29-447"><a href="#cb29-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-448"><a href="#cb29-448" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-449"><a href="#cb29-449" aria-hidden="true" tabindex="-1"></a><span class="in">@carmichael_1954 suggests something is true.</span></span>
<span id="cb29-450"><a href="#cb29-450" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-451"><a href="#cb29-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-452"><a href="#cb29-452" aria-hidden="true" tabindex="-1"></a>The output of this is:</span>
<span id="cb29-453"><a href="#cb29-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-454"><a href="#cb29-454" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; @carmichael_1954 suggests something is true.</span></span>
<span id="cb29-455"><a href="#cb29-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-456"><a href="#cb29-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-457"><a href="#cb29-457" aria-hidden="true" tabindex="-1"></a>:::fyi</span>
<span id="cb29-458"><a href="#cb29-458" aria-hidden="true" tabindex="-1"></a>You can learn more on the <span class="co">[</span><span class="ot">Citations and Footnotes Help Page</span><span class="co">](https://quarto.org/docs/authoring/footnotes-and-citations.html)</span> in the Quarto documentation.</span>
<span id="cb29-459"><a href="#cb29-459" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb29-460"><a href="#cb29-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-461"><a href="#cb29-461" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-462"><a href="#cb29-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-463"><a href="#cb29-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-464"><a href="#cb29-464" aria-hidden="true" tabindex="-1"></a><span class="fu">### Use APA Formatted Citations and References</span></span>
<span id="cb29-465"><a href="#cb29-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-466"><a href="#cb29-466" aria-hidden="true" tabindex="-1"></a>By default, citations and references are formatted using the Chicago style. To use another style, you will need to:</span>
<span id="cb29-467"><a href="#cb29-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-468"><a href="#cb29-468" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Download the appropriate citation style language (CSL) file. (Find many at https://zotero.org/styles)</span>
<span id="cb29-469"><a href="#cb29-469" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Place the CSL file in the <span class="in">`assets`</span> folder of your project's directory.</span>
<span id="cb29-470"><a href="#cb29-470" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Specify the name of the CSL style file in the <span class="in">`csl:`</span> key in the QMD file's YAML.</span>
<span id="cb29-471"><a href="#cb29-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-472"><a href="#cb29-472" aria-hidden="true" tabindex="-1"></a>For example, say you have downloaded and saved the <span class="in">`apa.csl`</span> file  and placed it in the <span class="in">`assets`</span> directory, giving the following directory/folder structure:</span>
<span id="cb29-473"><a href="#cb29-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-474"><a href="#cb29-474" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-475"><a href="#cb29-475" aria-hidden="true" tabindex="-1"></a><span class="in">assignment-01</span></span>
<span id="cb29-476"><a href="#cb29-476" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── README</span></span>
<span id="cb29-477"><a href="#cb29-477" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── assets</span></span>
<span id="cb29-478"><a href="#cb29-478" aria-hidden="true" tabindex="-1"></a><span class="in">       ├── apa.csl</span></span>
<span id="cb29-479"><a href="#cb29-479" aria-hidden="true" tabindex="-1"></a><span class="in">       └── my-bibliography.bib</span></span>
<span id="cb29-480"><a href="#cb29-480" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── assignment-01.qmd</span></span>
<span id="cb29-481"><a href="#cb29-481" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── assignment-01.Rproj</span></span>
<span id="cb29-482"><a href="#cb29-482" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── data</span></span>
<span id="cb29-483"><a href="#cb29-483" aria-hidden="true" tabindex="-1"></a><span class="in">       └── fertility.csv</span></span>
<span id="cb29-484"><a href="#cb29-484" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── figs</span></span>
<span id="cb29-485"><a href="#cb29-485" aria-hidden="true" tabindex="-1"></a><span class="in">    └── scripts</span></span>
<span id="cb29-486"><a href="#cb29-486" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-487"><a href="#cb29-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-488"><a href="#cb29-488" aria-hidden="true" tabindex="-1"></a>You would include the following in your YAML.</span>
<span id="cb29-489"><a href="#cb29-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-490"><a href="#cb29-490" aria-hidden="true" tabindex="-1"></a>If, for example, you had named the BIB file <span class="in">`my-bibliography.bib`</span> and had put this file in the <span class="in">`assets`</span> directory, your YAML would be:</span>
<span id="cb29-491"><a href="#cb29-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-492"><a href="#cb29-492" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-493"><a href="#cb29-493" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-494"><a href="#cb29-494" aria-hidden="true" tabindex="-1"></a><span class="in">title: "Assignment 1"</span></span>
<span id="cb29-495"><a href="#cb29-495" aria-hidden="true" tabindex="-1"></a><span class="in">subtitle: "Introduction to Quarto"</span></span>
<span id="cb29-496"><a href="#cb29-496" aria-hidden="true" tabindex="-1"></a><span class="in">author: "Your Group's Names"</span></span>
<span id="cb29-497"><a href="#cb29-497" aria-hidden="true" tabindex="-1"></a><span class="in">date: "January XX, 2023"</span></span>
<span id="cb29-498"><a href="#cb29-498" aria-hidden="true" tabindex="-1"></a><span class="in">format: html</span></span>
<span id="cb29-499"><a href="#cb29-499" aria-hidden="true" tabindex="-1"></a><span class="in">editor: visual</span></span>
<span id="cb29-500"><a href="#cb29-500" aria-hidden="true" tabindex="-1"></a><span class="in">bibliography: "assets/my-bibliography.bib"</span></span>
<span id="cb29-501"><a href="#cb29-501" aria-hidden="true" tabindex="-1"></a><span class="in">csl: "assets/apa-single-spaced.csl"</span></span>
<span id="cb29-502"><a href="#cb29-502" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-503"><a href="#cb29-503" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-504"><a href="#cb29-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-505"><a href="#cb29-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-506"><a href="#cb29-506" aria-hidden="true" tabindex="-1"></a>Use of the APA CSL file not only formats the references according to APA format, but it also fixed the order of the citations in the text itself! (Even though we included the Ross citation identifier prior to the Carmichael citation identifier in the multiple references example, the APA CSL file put them in the text alphabetically!)</span>
<span id="cb29-507"><a href="#cb29-507" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-508"><a href="#cb29-508" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-509"><a href="#cb29-509" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-510"><a href="#cb29-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-511"><a href="#cb29-511" aria-hidden="true" tabindex="-1"></a><span class="fu">### Citation Extras</span></span>
<span id="cb29-512"><a href="#cb29-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-513"><a href="#cb29-513" aria-hidden="true" tabindex="-1"></a>One R package that is extremely useful, especially if you are using the visual editor in RStudio for writing QMD documents, is <span class="in">`{citr}`</span>. This package provides functionality and an RStudio Add-In to search a BibTeX-file to create and insert formatted Markdown citations into a QMD document.</span>
<span id="cb29-514"><a href="#cb29-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-517"><a href="#cb29-517" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-518"><a href="#cb29-518" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb29-519"><a href="#cb29-519" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Screenshot of the citr package."</span></span>
<span id="cb29-520"><a href="#cb29-520" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figs/02-citr-package.png"</span>)</span>
<span id="cb29-521"><a href="#cb29-521" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-522"><a href="#cb29-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-523"><a href="#cb29-523" aria-hidden="true" tabindex="-1"></a>The <span class="in">`{citr}`</span> package is only available via GitHub, so you will need to install it using <span class="in">`{remotes}`</span> or <span class="in">`{devtools}`</span>. (See the Computational Toolkit book for a reminder on how to do this.) The directions for installing <span class="in">`{citr}`</span> are also on the <span class="co">[</span><span class="ot">citr webpage</span><span class="co">](https://github.com/crsh/citr)</span> along with instructions for using the package. </span>
<span id="cb29-524"><a href="#cb29-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-525"><a href="#cb29-525" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-526"><a href="#cb29-526" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-527"><a href="#cb29-527" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-528"><a href="#cb29-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-529"><a href="#cb29-529" aria-hidden="true" tabindex="-1"></a><span class="fu"># Auto-Populating the Date in Your YAML</span></span>
<span id="cb29-530"><a href="#cb29-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-531"><a href="#cb29-531" aria-hidden="true" tabindex="-1"></a>We can auto-populate the <span class="in">`date:`</span> key in our document's YAML by including "today".</span>
<span id="cb29-532"><a href="#cb29-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-533"><a href="#cb29-533" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-534"><a href="#cb29-534" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-535"><a href="#cb29-535" aria-hidden="true" tabindex="-1"></a><span class="in">title: "Assignment 1"</span></span>
<span id="cb29-536"><a href="#cb29-536" aria-hidden="true" tabindex="-1"></a><span class="in">subtitle: "Introduction to Quarto"</span></span>
<span id="cb29-537"><a href="#cb29-537" aria-hidden="true" tabindex="-1"></a><span class="in">author: "Your Group's Names"</span></span>
<span id="cb29-538"><a href="#cb29-538" aria-hidden="true" tabindex="-1"></a><span class="in">date: "today"</span></span>
<span id="cb29-539"><a href="#cb29-539" aria-hidden="true" tabindex="-1"></a><span class="in">format: html</span></span>
<span id="cb29-540"><a href="#cb29-540" aria-hidden="true" tabindex="-1"></a><span class="in">editor: visual</span></span>
<span id="cb29-541"><a href="#cb29-541" aria-hidden="true" tabindex="-1"></a><span class="in">bibliography: "assets/my-bibliography.bib"</span></span>
<span id="cb29-542"><a href="#cb29-542" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-543"><a href="#cb29-543" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-544"><a href="#cb29-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-545"><a href="#cb29-545" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-546"><a href="#cb29-546" aria-hidden="true" tabindex="-1"></a>You can also use an inline code chunk that calls the <span class="in">`Sys.Date()`</span> function. This function returns your computer's idea of the current date in the <span class="in">`YYYY-MM-DD`</span> format (ISO 8601 standard). If you want to be hyper specific, you can use <span class="in">`Sys.time()`</span> to return the date and time in the format: <span class="in">`YYYY-MM-DD HH-MM:SS Time Zone`</span>.</span>
<span id="cb29-547"><a href="#cb29-547" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-550"><a href="#cb29-550" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb29-551"><a href="#cb29-551" aria-hidden="true" tabindex="-1"></a><span class="co"># Return date</span></span>
<span id="cb29-552"><a href="#cb29-552" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.Date</span>()</span>
<span id="cb29-553"><a href="#cb29-553" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-554"><a href="#cb29-554" aria-hidden="true" tabindex="-1"></a><span class="co"># Return time</span></span>
<span id="cb29-555"><a href="#cb29-555" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.time</span>()</span>
<span id="cb29-556"><a href="#cb29-556" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-557"><a href="#cb29-557" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-558"><a href="#cb29-558" aria-hidden="true" tabindex="-1"></a>Here is an example of the YAML in the <span class="in">`date:`</span> key to use <span class="in">`Sys.Date()`</span> to auto-populate the date.</span>
<span id="cb29-559"><a href="#cb29-559" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-560"><a href="#cb29-560" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-561"><a href="#cb29-561" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-562"><a href="#cb29-562" aria-hidden="true" tabindex="-1"></a><span class="in">title: "Assignment 1"</span></span>
<span id="cb29-563"><a href="#cb29-563" aria-hidden="true" tabindex="-1"></a><span class="in">subtitle: "Introduction to Quarto"</span></span>
<span id="cb29-564"><a href="#cb29-564" aria-hidden="true" tabindex="-1"></a><span class="in">author: "Your Group's Names"</span></span>
<span id="cb29-565"><a href="#cb29-565" aria-hidden="true" tabindex="-1"></a><span class="in">date: " `r knitr::inline_expr("Sys.Date()")` "</span></span>
<span id="cb29-566"><a href="#cb29-566" aria-hidden="true" tabindex="-1"></a><span class="in">format: html</span></span>
<span id="cb29-567"><a href="#cb29-567" aria-hidden="true" tabindex="-1"></a><span class="in">editor: visual</span></span>
<span id="cb29-568"><a href="#cb29-568" aria-hidden="true" tabindex="-1"></a><span class="in">bibliography: "assets/my-bibliography.bib"</span></span>
<span id="cb29-569"><a href="#cb29-569" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-570"><a href="#cb29-570" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-571"><a href="#cb29-571" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-572"><a href="#cb29-572" aria-hidden="true" tabindex="-1"></a>Note that the inline chunk is embedded in quotation marks. We can custom format each of these using the <span class="in">`format()`</span> function. This function takes the <span class="in">`Sys.Date()`</span> function as its first argument, and then a character string of formatting rules. Here I format the date to have the full month name, day of the month, and year (with century): e.g., January 12, 2023.</span>
<span id="cb29-573"><a href="#cb29-573" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-574"><a href="#cb29-574" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-575"><a href="#cb29-575" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-576"><a href="#cb29-576" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-577"><a href="#cb29-577" aria-hidden="true" tabindex="-1"></a><span class="in">title: "Assignment 1"</span></span>
<span id="cb29-578"><a href="#cb29-578" aria-hidden="true" tabindex="-1"></a><span class="in">subtitle: "Introduction to Quarto"</span></span>
<span id="cb29-579"><a href="#cb29-579" aria-hidden="true" tabindex="-1"></a><span class="in">author: "Your Group's Names"</span></span>
<span id="cb29-580"><a href="#cb29-580" aria-hidden="true" tabindex="-1"></a><span class="in">date: " `r knitr::inline_expr("format(Sys.Date(), '%B %d %Y')")`"</span></span>
<span id="cb29-581"><a href="#cb29-581" aria-hidden="true" tabindex="-1"></a><span class="in">format: html</span></span>
<span id="cb29-582"><a href="#cb29-582" aria-hidden="true" tabindex="-1"></a><span class="in">editor: visual</span></span>
<span id="cb29-583"><a href="#cb29-583" aria-hidden="true" tabindex="-1"></a><span class="in">bibliography: "assets/my-bibliography.bib"</span></span>
<span id="cb29-584"><a href="#cb29-584" aria-hidden="true" tabindex="-1"></a><span class="in">---</span></span>
<span id="cb29-585"><a href="#cb29-585" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb29-586"><a href="#cb29-586" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-587"><a href="#cb29-587" aria-hidden="true" tabindex="-1"></a>You can see all the formatting options by calling <span class="in">`help(strptime)`</span>.</span>
<span id="cb29-588"><a href="#cb29-588" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-589"><a href="#cb29-589" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-590"><a href="#cb29-590" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-591"><a href="#cb29-591" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-592"><a href="#cb29-592" aria-hidden="true" tabindex="-1"></a><span class="fu">## Learn More</span></span>
<span id="cb29-593"><a href="#cb29-593" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-594"><a href="#cb29-594" aria-hidden="true" tabindex="-1"></a>Yihui Xie, the creater of the RMarkdown package (which does a lot of the work in converting your QMD file to an HTML/PDF file, gave a nice trechnical talk to the *American Statistical Association's Section on Statistical Computing* that explain what actually happens behind the scenes when you click the <span class="in">`Knit`</span> or <span class="in">`Render`</span> button in RStudio to render a RMD or QMD document.</span>
<span id="cb29-595"><a href="#cb29-595" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-596"><a href="#cb29-596" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">An anatomy of R Markdown with minimal applications </span><span class="co">](https://www.youtube.com/watch?v=fiy32LjgGUE)</span></span>
<span id="cb29-597"><a href="#cb29-597" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-598"><a href="#cb29-598" aria-hidden="true" tabindex="-1"></a>&lt;br /&gt;</span>
<span id="cb29-599"><a href="#cb29-599" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-600"><a href="#cb29-600" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-601"><a href="#cb29-601" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
<span id="cb29-602"><a href="#cb29-602" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-603"><a href="#cb29-603" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-604"><a href="#cb29-604" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-605"><a href="#cb29-605" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>